
#line 2 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 158
#define YY_END_OF_BUFFER 159
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[560] =
    {   0,
        0,    0,   17,   17,  159,  157,   14,   13,   50,  157,
      157,   41,   44,  157,   28,   29,   39,   37,   81,   38,
       35,   40,  150,  150,   31,   30,   53,   52,   54,   33,
      147,  147,   24,   26,   42,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,   20,   46,   22,   48,   17,
       18,   14,   71,    0,  155,    0,    0,   59,   23,   75,
       62,    0,  153,    0,   57,   79,   55,   80,   56,   83,
       36,    0,  151,   16,    0,   58,  151,  149,  150,    0,
      150,  150,    0,   34,   27,   21,   25,   66,   73,   70,

       74,   67,  147,    0,    0,   60,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,   97,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  110,  147,  147,
      147,  147,  147,  147,  147,   78,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,   64,   77,   17,   18,   18,   19,
        0,  155,    0,    0,    0,  153,    0,   82,   32,    0,
      151,    0,   15,  149,  149,    0,  152,  150,  150,  148,
       68,   69,    0,  156,    0,    0,  154,    0,   76,   84,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,

      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      107,  147,  147,  147,  112,  147,  147,  147,  116,   51,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  135,  147,
      147,  147,  147,  147,  147,  147,  147,  147,   43,    0,
        0,  151,  149,  149,  152,  148,  148,    0,  156,    0,
        0,  154,    0,  147,   85,  147,  147,   86,  147,   88,
      147,   90,  147,  147,  147,  147,  147,  147,  147,  147,
      100,  101,  147,  147,  147,  147,  147,  147,  109,  147,
      113,  147,  147,  147,  147,  147,  147,  147,  147,  147,

      147,  147,  147,  147,  147,  147,  147,  147,  147,  132,
      147,  134,  147,  147,  147,  147,  147,  143,  147,  147,
      147,  147,    0,  148,  148,  147,  147,   47,   87,   89,
       91,   49,   92,  147,  147,  147,  147,  147,  147,  147,
      147,  105,  106,  147,  147,  147,  147,  147,  147,   65,
      147,  147,  147,  147,  147,  147,  124,  147,  147,  147,
      147,  147,  147,  133,  147,  147,  147,  139,  147,  141,
      147,  147,  147,  146,  147,    0,   63,   45,  147,  147,
      147,   96,   98,  147,  147,  103,  104,  108,  111,  147,
      147,   72,  147,  147,  147,  120,  147,  147,  123,  125,

      126,  127,  129,  130,  147,  147,  137,  147,  147,    0,
      147,  147,  147,   61,    0,  147,  147,   95,  147,  147,
      114,  147,  147,  118,  147,  147,  147,  147,  147,  136,
      147,  147,    0,  142,  147,  145,    0,  147,   94,  147,
      102,  147,  117,  147,  121,  147,  147,  131,  138,  140,
        0,  144,    0,    0,  147,  147,  115,  119,  147,  147,
        0,    0,    0,    0,   93,  147,  147,  147,    0,    0,
        0,    0,    0,    0,   11,  147,  147,  128,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   99,  147,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  147,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  147,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  147,    0,    4,    0,    0,    2,    0,
        0,    0,    0,    0,    0,  122,    0,    0,    0,    0,
        0,    0,    0,    0,   10,    0,    5,    6,    7,    9,
        3,    0,    0,    0,    1,    8,    0,   12,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   31,   31,   33,   31,   31,   34,   31,   31,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   31,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[69] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    1,    1,    1,    4,    4,
        4,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        5,    5,    5,    5,    1,    2,    1,    1,    5,    4,
        4,    4,    4,    4,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[575] =
    {   0,
        0,    0,  742,  741,  753,  756,   67,  756,  727,   64,
      703,   47,   65,   65,  756,  756,  725,   62,  756,   63,
       64,   73,   85,   92,   56,  756,   72,  724,   67,  756,
        0,   89,  756,  756,  723,   51,   67,   87,   63,   81,
       99,  694,   93,  693,  686,   88,   92,   94,  700,  109,
      115,  106,  112,  119,  690,  756,  129,  756,  756,    0,
      151,  170,  756,  162,  756,  170,  690,  756,  756,  756,
      756,  165,  756,  174,  756,  756,  756,  756,  756,  728,
      756,  723,  167,  756,  736,  756,  184,  203,  222,  244,
      148,  150,    0,  756,  756,  756,  756,  713,  756,  756,

      756,  712,    0,  173,  179,  756,  693,  684,  676,  675,
      679,  687,  133,  690,  689,  141,  135,  669,  675,  669,
      666,  167,  674,  670,  666,  673,  662,    0,   72,  667,
      660,  666,  655,  657,  670,  674,  178,  671,  192,  658,
      173,  162,  662,  658,  196,  186,  654,  200,  659,  650,
      211,  658,  656,  647,  756,  756,    0,  255,  256,  756,
      240,  250,  264,  660,  261,  265,  274,  756,  756,  269,
      756,  698,  756,  245,  248,  272,  275,  756,  756,  276,
      756,  756,  276,  756,  296,  277,  756,  308,  661,    0,
      646,  263,  648,  657,  652,  653,  638,  636,  638,  257,

      651,  646,  648,  648,  643,  635,  177,  641,  627,  643,
        0,  638,  628,  632,    0,  633,  638,  633,    0,  637,
      619,  630,  613,  614,  621,  622,  617,  609,  611,  614,
      621,  606,  604,  604,  607,  603,  606,  614,    0,  613,
      603,  607,  602,  595,  609,  611,  610,  599,  609,  597,
      302,  308,  756,  756,  756,  284,  274,  313,  324,  328,
      323,  326,  336,  602,    0,  593,  588,    0,  594,    0,
      595,    0,  584,  590,  581,  590,  578,  578,  585,  583,
        0,    0,  585,  576,  575,  586,  571,  576,    0,  575,
        0,  585,  568,  580,  583,  567,  581,  576,  571,  561,

      559,  560,  557,  570,  560,  564,  569,  568,  559,    0,
      547,    0,  299,  555,  560,  559,  545,    0,  545,  546,
      557,  556,  540,  756,  756,  543,  554,    0,    0,    0,
        0,    0,  557,  543,  544,  549,  548,  543,  548,  531,
      536,    0,    0,  544,  542,  535,  530,  528,  524,    0,
      523,  538,  537,  520,  533,  524,    0,  532,  529,  531,
      514,  524,  530,    0,  525,  525,  527,    0,  514,  561,
      524,  515,  523,    0,  506,  517,    0,    0,  517,  499,
      499,    0,    0,  514,  507,    0,    0,    0,    0,  510,
      513,    0,  499,  507,  492,    0,  505,  492,    0,    0,

        0,  508,    0,    0,  488,  500,    0,  493,  499,  490,
      491,  490,  481,    0,  494,  497,  492,    0,  496,  476,
        0,  491,  476,    0,  487,  474,  475,  486,  483,    0,
      482,  482,  484,    0,  479,    0,  344,  465,    0,  479,
        0,  476,    0,  476,    0,  462,  477,    0,    0,    0,
      465,    0,  350,    0,  457,  474,    0,    0,  469,  455,
      467,  351,  323,  504,    0,  452,  450,  449,  449,  312,
      448,  292,  459,  445,  756,  444,  462,    0,  446,  459,
      440,  449,  438,  438,  310,  437,  437,    0,  450,  451,
      432,  323,  438,  432,  429,  446,  427,  426,  435,  442,

      439,  433,  429,  430,  433,  432,  419,  422,  417,  416,
      419,  413,  425,  442,  419,  414,  439,  424,  419,  414,
      417,  416,  413,  400,  453,  756,  415,  409,  756,  403,
      402,  398,  411,  410,  423,    0,  391,  418,  374,  352,
      351,  349,  322,  301,  756,  283,  756,  756,  756,  756,
      756,  253,  207,  165,  756,  756,  171,  756,  756,  380,
      385,  390,  392,  397,  402,  407,  412,  417,  179,  422,
      427,  432,  437,  442
    } ;

static const flex_int16_t yy_def[575] =
    {   0,
      559,    1,  560,  560,  559,  559,  559,  559,  559,  561,
      559,  559,  559,  562,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      563,  563,  559,  559,  559,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  559,  559,  559,  559,  564,
      565,  559,  559,  561,  559,  566,  559,  559,  559,  559,
      559,  562,  559,  567,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559,  568,  559,  559,  559,  559,  559,
      559,  559,  569,  559,  559,  559,  559,  559,  559,  559,

      559,  559,  563,  570,  571,  559,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  559,  559,  564,  565,  565,  559,
      561,  561,  566,  559,  562,  562,  567,  559,  559,  559,
      559,  568,  559,  559,  559,  559,  559,  559,  559,  569,
      559,  559,  570,  559,  572,  571,  559,  573,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  559,
      559,  559,  559,  559,  559,  559,  559,  570,  570,  572,
      571,  571,  573,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  559,  559,  559,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  559,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,

      563,  563,  563,  563,  563,  563,  563,  563,  563,  559,
      563,  563,  563,  563,  559,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  559,  563,  563,  563,  559,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      559,  563,  559,  574,  563,  563,  563,  563,  563,  563,
      559,  559,  559,  574,  563,  563,  563,  563,  559,  559,
      559,  559,  559,  559,  559,  563,  563,  563,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  563,  563,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  563,

      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  563,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  563,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  563,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  559,    0,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559
    } ;

static const flex_int16_t yy_nxt[825] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       24,   25,   26,   27,   28,   29,   30,   31,   31,   31,
       31,   32,   31,   31,   33,    6,   34,   35,   31,   36,
       37,   38,   39,   40,   41,   42,   31,   43,   31,   44,
       45,   46,   47,   48,   31,   49,   50,   51,   52,   53,
       54,   55,   31,   31,   56,   57,   58,   59,   62,   65,
       62,   68,   69,   70,   73,   76,   81,   94,   78,   96,
       82,   95,   83,   83,   83,   84,   77,   79,   80,   71,
       85,  101,  102,   97,  104,   98,   99,   86,  105,   66,

       74,   87,  107,   88,   88,   89,  117,  108,   87,  109,
       89,   89,   89,   90,  110,  118,   91,   92,   93,  111,
       90,  214,  112,   91,   92,  119,  113,  132,   90,  215,
      120,  133,  121,  114,   91,   90,  115,  128,  123,  116,
      134,   91,  122,   92,  129,  135,   93,  136,  124,  137,
       92,  125,  138,  155,  126,  140,  141,  148,  144,  150,
      152,  145,  149,  159,  151,  153,  142,   65,  160,  143,
      146,   62,   64,   62,   73,  162,   72,  147,  184,  201,
      178,  179,  180,  166,  202,   83,   83,   83,  187,  195,
      196,  199,  200,  558,  156,  170,  171,   66,  171,  179,

       74,  232,   83,   83,   83,  163,  178,  557,  185,  167,
      170,  171,  170,  171,  188,  171,  171,  233,  230,   87,
      207,   88,   88,   89,  208,  223,  283,  170,  171,  284,
      224,   90,  556,  171,  174,  175,  231,  226,   87,  227,
       89,   89,   89,  236,  238,   65,   90,  241,  239,  228,
       90,  237,  174,   91,   92,   65,  242,  176,  245,  176,
      246,  175,  177,  177,  177,   90,   64,  559,  159,  162,
       73,   91,  559,  160,   73,   66,   72,  253,  555,  254,
       92,  184,  251,  166,  251,   66,  187,  252,  252,  252,
      177,  177,  177,  177,  177,  177,   74,  254,  183,  163,

       74,  259,  266,  253,  255,  325,  255,  256,  257,  167,
      186,  185,  188,  275,  276,  267,  324,  262,  184,  255,
      252,  252,  252,  325,  255,  256,  252,  252,  252,  184,
      183,  260,  187,  259,  257,  187,  484,  171,  186,  171,
      554,  365,  324,  263,  485,  262,  366,  453,  185,  454,
      367,  553,  171,  462,  462,  454,  454,  171,  188,  185,
      496,  188,  480,  260,  470,  503,  497,  471,  481,  482,
      472,  263,  552,  463,  551,  473,  550,  549,  504,  474,
       60,   60,   60,   60,   60,   64,   64,   64,   64,   64,
       72,   72,   72,   72,   72,  103,  103,  157,  157,  548,

      157,  157,  158,  158,  158,  158,  158,  161,  161,  161,
      161,  161,  165,  165,  165,  165,  165,  172,  172,  172,
      172,  172,  183,  183,  183,  183,  183,  186,  186,  186,
      186,  186,  258,  258,  258,  258,  258,  261,  261,  261,
      261,  261,  464,  547,  464,  464,  464,  546,  545,  544,
      543,  542,  541,  540,  539,  538,  537,  536,  535,  534,
      533,  532,  531,  530,  529,  528,  527,  526,  525,  524,
      523,  522,  521,  520,  519,  518,  517,  516,  515,  514,
      513,  512,  511,  510,  509,  508,  507,  506,  505,  502,
      501,  500,  499,  498,  495,  494,  493,  492,  491,  490,

      489,  488,  487,  486,  483,  479,  478,  477,  476,  475,
      469,  468,  467,  466,  465,  461,  460,  459,  458,  457,
      456,  455,  452,  451,  450,  449,  448,  447,  446,  445,
      444,  443,  442,  441,  440,  439,  438,  437,  436,  435,
      434,  433,  432,  431,  430,  429,  428,  427,  426,  425,
      424,  423,  422,  421,  420,  419,  418,  417,  416,  415,
      414,  413,  412,  411,  410,  409,  408,  407,  406,  405,
      404,  403,  402,  401,  400,  399,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  385,
      384,  383,  382,  381,  380,  379,  378,  377,  376,  375,

      374,  373,  372,  371,  370,  369,  368,  364,  363,  362,
      361,  360,  359,  358,  357,  356,  355,  354,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  344,  343,  342,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  282,  281,  280,  279,  278,
      277,  274,  273,  272,  271,  270,  269,  268,  265,  264,

      173,  250,  249,  248,  247,  244,  243,  240,  235,  234,
      229,  225,  222,  221,  220,  219,  218,  217,  216,  213,
      212,  211,  210,  209,  206,  205,  204,  203,  198,  197,
      194,  193,  192,  191,  190,  189,  182,  181,  173,  169,
      168,  164,  154,  139,  131,  130,  127,  106,  100,   75,
       67,   63,  559,   61,   61,    5,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,

      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559
    } ;

static const flex_int16_t yy_chk[825] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    7,   10,
        7,   12,   12,   13,   14,   18,   21,   25,   20,   27,
       21,   25,   21,   21,   21,   22,   18,   20,   20,   13,
       22,   29,   29,   27,   32,   27,   27,   22,   32,   10,

       14,   23,   36,   23,   23,   23,   39,   36,   24,   36,
       24,   24,   24,   23,   37,   39,   23,   23,   23,   37,
       24,  129,   37,   24,   24,   39,   38,   46,   23,  129,
       40,   46,   40,   38,   23,   24,   38,   43,   41,   38,
       46,   24,   40,   23,   43,   47,   23,   47,   41,   48,
       24,   41,   48,   57,   41,   50,   50,   52,   51,   53,
       54,   51,   52,   61,   53,   54,   50,   64,   61,   50,
       51,   62,   66,   62,   72,   66,   74,   51,  104,  117,
       91,   92,  569,   74,  117,   83,   83,   83,  105,  113,
      113,  116,  116,  557,   57,   83,   83,   64,   83,   92,

       72,  142,   87,   87,   87,   66,   91,  554,  104,   74,
       83,   83,   87,   87,  105,   87,   83,  142,  141,   88,
      122,   88,   88,   88,  122,  137,  207,   87,   87,  207,
      137,   88,  553,   87,   88,   88,  141,  139,   89,  139,
       89,   89,   89,  145,  146,  161,   88,  148,  146,  139,
       89,  145,   88,   89,   89,  162,  148,   90,  151,   90,
      151,   88,   90,   90,   90,   89,  163,  158,  159,  163,
      165,   89,  158,  159,  166,  161,  167,  174,  552,  175,
       89,  183,  170,  167,  170,  162,  186,  170,  170,  170,
      176,  176,  176,  177,  177,  177,  165,  175,  185,  163,

      166,  185,  192,  174,  177,  257,  177,  180,  180,  167,
      188,  183,  186,  200,  200,  192,  256,  188,  258,  177,
      251,  251,  251,  257,  177,  180,  252,  252,  252,  259,
      260,  185,  261,  260,  180,  262,  472,  252,  263,  252,
      546,  313,  256,  188,  472,  263,  313,  437,  258,  437,
      313,  544,  252,  453,  462,  453,  462,  252,  261,  259,
      485,  262,  470,  260,  463,  492,  485,  463,  470,  470,
      463,  263,  543,  453,  542,  463,  541,  540,  492,  463,
      560,  560,  560,  560,  560,  561,  561,  561,  561,  561,
      562,  562,  562,  562,  562,  563,  563,  564,  564,  539,

      564,  564,  565,  565,  565,  565,  565,  566,  566,  566,
      566,  566,  567,  567,  567,  567,  567,  568,  568,  568,
      568,  568,  570,  570,  570,  570,  570,  571,  571,  571,
      571,  571,  572,  572,  572,  572,  572,  573,  573,  573,
      573,  573,  574,  538,  574,  574,  574,  537,  535,  534,
      533,  532,  531,  530,  528,  527,  525,  524,  523,  522,
      521,  520,  519,  518,  517,  516,  515,  514,  513,  512,
      511,  510,  509,  508,  507,  506,  505,  504,  503,  502,
      501,  500,  499,  498,  497,  496,  495,  494,  493,  491,
      490,  489,  487,  486,  484,  483,  482,  481,  480,  479,

      477,  476,  474,  473,  471,  469,  468,  467,  466,  464,
      461,  460,  459,  456,  455,  451,  447,  446,  444,  442,
      440,  438,  435,  433,  432,  431,  429,  428,  427,  426,
      425,  423,  422,  420,  419,  417,  416,  415,  413,  412,
      411,  410,  409,  408,  406,  405,  402,  398,  397,  395,
      394,  393,  391,  390,  385,  384,  381,  380,  379,  376,
      375,  373,  372,  371,  370,  369,  367,  366,  365,  363,
      362,  361,  360,  359,  358,  356,  355,  354,  353,  352,
      351,  349,  348,  347,  346,  345,  344,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  327,  326,  323,  322,

      321,  320,  319,  317,  316,  315,  314,  311,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  290,  288,  287,  286,
      285,  284,  283,  280,  279,  278,  277,  276,  275,  274,
      273,  271,  269,  267,  266,  264,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  218,  217,  216,  214,
      213,  212,  210,  209,  208,  206,  205,  204,  203,  202,
      201,  199,  198,  197,  196,  195,  194,  193,  191,  189,

      172,  164,  154,  153,  152,  150,  149,  147,  144,  143,
      140,  138,  136,  135,  134,  133,  132,  131,  130,  127,
      126,  125,  124,  123,  121,  120,  119,  118,  115,  114,
      112,  111,  110,  109,  108,  107,  102,   98,   85,   82,
       80,   67,   55,   49,   45,   44,   42,   35,   28,   17,
       11,    9,    5,    4,    3,  559,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,

      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  559,  559
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[159] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "120++lex.l"
/*	$Id: lexer.l,v 1.2 1997/11/19 15:13:15 sandro Exp $	*/
/*
 * Copyright (c) 1997 Sandro Sigala <ssigala@globalnet.it>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * ISO C++ lexical analyzer.
 *
 * Based on the ISO C++ draft standard of December '96.
 */
#line 35 "120++lex.l"

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <ctype.h>
#include <libgen.h>
#include <string.h>

#include "120++gram.h"
#include "tree.h"
#include "tlist.h"
#include "hasht.h"
#include "list.h"

#include "args.h"
#include "logger.h"
#include "libs.h"
#include "rules.h"
#include "symt.h"
#include "token.h"


#define T(name) do { prepare_token(name); return name; } while(0)
#define YYAPPENDTEXT() token_push_text(yytoken, yytext)
#define YYAPPENDCHAR(character) token_push_sval_char(yytoken, character)


int lineno;

//static void skip_until_eol(void);
//static void skip_comment(void);
static int check_identifier( char *s, tableptr t);

void typenametable_insert(char *s, tableptr t);
//void classnametable_insert( node, tableptr );
void handle_include();
int tokenize(int);
static void prepare_token(int category);
struct node *tree_new(struct node *parent, void *data,
bool (*compare)(void *a, void *b),
void (*delete)(void *data, bool leaf));
void delete_tree(void *data, bool leaf);
//void EOF();

int errors = 0;
tok_1 yytoken;

/* #include flags */
int ctime = 0;
int iostream = 0;
int iomanip = 0;
int cmath = 0;
int cstdlib = 0;
int cstring = 0;
int fstream = 0;
int string = 0;
int usingnamespacestd = 0;
int ofstream = 0;
int ifstream = 0;


/* extern */
extern FILE *yyin;
//extern int yylineno;
extern char *yytext;
extern int yychar;
extern YYSTYPE yylval;
extern struct hasht *yytypes;
extern struct list *yyfiles;
extern struct list *yyclibs;
extern struct hasht *yyincludes;
extern tableptr classtable;
extern nodeptr filestack;


#line 950 "<stdout>"
#define YY_NO_INPUT 1

#line 953 "<stdout>"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 127 "120++lex.l"


#line 1172 "<stdout>"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 560 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 756 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 129 "120++lex.l"
{ iostream = 1;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 130 "120++lex.l"
{ ctime = 1; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 131 "120++lex.l"
{ iomanip = 1; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 132 "120++lex.l"
{ cmath = 1; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 133 "120++lex.l"
{ cstdlib = 1; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 134 "120++lex.l"
{ cstring = 1; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 135 "120++lex.l"
{ fstream = 1; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 136 "120++lex.l"
{ ofstream = 1; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 137 "120++lex.l"
{ ifstream = 1; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 138 "120++lex.l"
{ string  = 1; }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 139 "120++lex.l"
{ handle_include(); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 140 "120++lex.l"
{ usingnamespacestd = 1;
    if ( string == 1 ) {
        
        typenametable_insert( "string" , classtable );
        
    };
    
    if ( iostream == 1 ) {
        
        typenametable_insert( "ifstream" , classtable );
        typenametable_insert( "ofstream" , classtable );
    };
    
}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 155 "120++lex.l"
{ ++lineno; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 156 "120++lex.l"
{ /* Ignore whitespace. */ }
	YY_BREAK
case 15:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 158 "120++lex.l"
{ /* eat C++ comments */ }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 160 "120++lex.l"
{ BEGIN(COMMENT); /* eat C comments */ }
	YY_BREAK

case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 163 "120++lex.l"
{ /* eat comment in chunks */ }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 164 "120++lex.l"
{ /* eat the lone star */ }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 165 "120++lex.l"
{ BEGIN(INITIAL); }
	YY_BREAK

case 20:
YY_RULE_SETUP
#line 168 "120++lex.l"
{ return tokenize('{'); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 169 "120++lex.l"
{ return tokenize('{'); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 170 "120++lex.l"
{ return tokenize('}'); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 171 "120++lex.l"
{ return tokenize('}'); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 172 "120++lex.l"
{ return tokenize('['); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 173 "120++lex.l"
{ return tokenize('['); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 174 "120++lex.l"
{ return tokenize(']'); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 175 "120++lex.l"
{ return tokenize(']'); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 176 "120++lex.l"
{ return tokenize('('); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 177 "120++lex.l"
{ return tokenize(')'); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 178 "120++lex.l"
{ return tokenize(';'); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 179 "120++lex.l"
{ return tokenize(':'); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 180 "120++lex.l"
{ return tokenize(ELLIPSIS); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 181 "120++lex.l"
{ return tokenize('?'); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 182 "120++lex.l"
{ return tokenize(COLONCOLON); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 183 "120++lex.l"
{ return tokenize('.'); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 184 "120++lex.l"
{ return tokenize(DOTSTAR); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 185 "120++lex.l"
{ return tokenize('+'); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 186 "120++lex.l"
{ return tokenize('-'); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 187 "120++lex.l"
{ return tokenize('*'); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 188 "120++lex.l"
{ return tokenize('/'); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 189 "120++lex.l"
{ return tokenize('%'); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 190 "120++lex.l"
{ return tokenize('^'); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 191 "120++lex.l"
{ return tokenize('^'); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 192 "120++lex.l"
{ return tokenize('&'); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 193 "120++lex.l"
{ return tokenize('&'); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 194 "120++lex.l"
{ return tokenize('|'); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 195 "120++lex.l"
{ return tokenize('|'); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 196 "120++lex.l"
{ return tokenize('~'); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 197 "120++lex.l"
{ return tokenize('~'); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 198 "120++lex.l"
{ return tokenize('!'); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 199 "120++lex.l"
{ return tokenize('!'); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 200 "120++lex.l"
{ return tokenize('='); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 201 "120++lex.l"
{ return tokenize('<'); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 202 "120++lex.l"
{ return tokenize('>'); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 203 "120++lex.l"
{ return tokenize(ADDEQ); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 204 "120++lex.l"
{ return tokenize(SUBEQ); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 205 "120++lex.l"
{ return tokenize(MULEQ); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 206 "120++lex.l"
{ return tokenize(DIVEQ); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 207 "120++lex.l"
{ return tokenize(MODEQ); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 208 "120++lex.l"
{ return tokenize(XOREQ); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 209 "120++lex.l"
{ return tokenize(XOREQ); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 210 "120++lex.l"
{ return tokenize(ANDEQ); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 211 "120++lex.l"
{ return tokenize(ANDEQ); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 212 "120++lex.l"
{ return tokenize(OREQ); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 213 "120++lex.l"
{ return tokenize(OREQ); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 214 "120++lex.l"
{ return tokenize(SL); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 215 "120++lex.l"
{ return tokenize(SR); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 216 "120++lex.l"
{ return tokenize(SLEQ); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 217 "120++lex.l"
{ return tokenize(SREQ); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 218 "120++lex.l"
{ return tokenize(EQ); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 219 "120++lex.l"
{ return tokenize(NOTEQ); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 220 "120++lex.l"
{ return tokenize(NOTEQ); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 221 "120++lex.l"
{ return tokenize(LTEQ); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 222 "120++lex.l"
{ return tokenize(GTEQ); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 223 "120++lex.l"
{ return tokenize(ANDAND); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 224 "120++lex.l"
{ return tokenize(ANDAND); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 225 "120++lex.l"
{ return tokenize(OROR); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 226 "120++lex.l"
{ return tokenize(OROR); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 227 "120++lex.l"
{ return tokenize(PLUSPLUS); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 228 "120++lex.l"
{ return tokenize(MINUSMINUS); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 229 "120++lex.l"
{ return tokenize(','); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 230 "120++lex.l"
{ return tokenize(ARROWSTAR); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 231 "120++lex.l"
{ return tokenize(ARROW); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 233 "120++lex.l"
{ return tokenize(ASM); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 234 "120++lex.l"
{ return tokenize(AUTO); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 235 "120++lex.l"
{ return tokenize(BOOL); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 236 "120++lex.l"
{ return tokenize(BREAK); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 237 "120++lex.l"
{ return tokenize(CASE); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 238 "120++lex.l"
{ return tokenize(CATCH); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 239 "120++lex.l"
{ return tokenize(CHAR); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 240 "120++lex.l"
{ return tokenize(CLASS); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 241 "120++lex.l"
{ return tokenize(CONST); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 242 "120++lex.l"
{ return tokenize(CONST_CAST); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 243 "120++lex.l"
{ return tokenize(CONTINUE); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 244 "120++lex.l"
{ return tokenize(DEFAULT); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 245 "120++lex.l"
{ return tokenize(DELETE); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 246 "120++lex.l"
{ return tokenize(DO); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 247 "120++lex.l"
{ return tokenize(DOUBLE); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 248 "120++lex.l"
{ return tokenize(DYNAMIC_CAST); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 249 "120++lex.l"
{ return tokenize(ELSE); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 250 "120++lex.l"
{ return tokenize(ENUM); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 251 "120++lex.l"
{ return tokenize(EXPLICIT); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 252 "120++lex.l"
{ return tokenize(EXPORT); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 253 "120++lex.l"
{ return tokenize(EXTERN); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 254 "120++lex.l"
{ return tokenize(FALSE); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 255 "120++lex.l"
{ return tokenize(FLOAT); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 256 "120++lex.l"
{ return tokenize(FOR); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 257 "120++lex.l"
{ return tokenize(FRIEND); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 258 "120++lex.l"
{ return tokenize(GOTO); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 259 "120++lex.l"
{ return tokenize(IF); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 260 "120++lex.l"
{ return tokenize(INLINE); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 261 "120++lex.l"
{ return tokenize(INT); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 262 "120++lex.l"
{ return tokenize(LONG); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 263 "120++lex.l"
{ return tokenize(MUTABLE); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 264 "120++lex.l"
{ return tokenize(NAMESPACE); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 265 "120++lex.l"
{ return tokenize(NEW); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 266 "120++lex.l"
{ return tokenize(OPERATOR); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 267 "120++lex.l"
{ return tokenize(PRIVATE); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 268 "120++lex.l"
{ return tokenize(PROTECTED); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 269 "120++lex.l"
{ return tokenize(PUBLIC); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 270 "120++lex.l"
{ return tokenize(REGISTER); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 271 "120++lex.l"
{ return tokenize(REINTERPRET_CAST); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 272 "120++lex.l"
{ return tokenize(RETURN); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 273 "120++lex.l"
{ return tokenize(SHORT); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 274 "120++lex.l"
{ return tokenize(SIGNED); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 275 "120++lex.l"
{ return tokenize(SIZEOF); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 276 "120++lex.l"
{ return tokenize(STATIC); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 277 "120++lex.l"
{ return tokenize(STATIC_CAST); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 278 "120++lex.l"
{ return tokenize(STRUCT); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 279 "120++lex.l"
{ return tokenize(SWITCH); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 280 "120++lex.l"
{ return tokenize(TEMPLATE); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 281 "120++lex.l"
{ return tokenize(THIS); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 282 "120++lex.l"
{ return tokenize(THROW); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 283 "120++lex.l"
{ return tokenize(TRUE); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 284 "120++lex.l"
{ return tokenize(TRY); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 285 "120++lex.l"
{ return tokenize(TYPEDEF); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 286 "120++lex.l"
{ return tokenize(TYPEID); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 287 "120++lex.l"
{ return tokenize(TYPENAME); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 288 "120++lex.l"
{ return tokenize(UNION); }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 289 "120++lex.l"
{ return tokenize(UNSIGNED); }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 290 "120++lex.l"
{ return tokenize(USING); }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 291 "120++lex.l"
{ return tokenize(VIRTUAL); }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 292 "120++lex.l"
{ return tokenize(VOID); }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 293 "120++lex.l"
{ return tokenize(VOLATILE); }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 294 "120++lex.l"
{ return tokenize(WCHAR_T); }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 295 "120++lex.l"
{ return tokenize(WHILE); }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 297 "120++lex.l"
{ return tokenize( check_identifier( yytext , classtable ) ); }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 299 "120++lex.l"
{ return tokenize(INTEGER); }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 300 "120++lex.l"
{ return tokenize(INTEGER); }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 301 "120++lex.l"
{ return tokenize(INTEGER); }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 303 "120++lex.l"
{ return tokenize(FLOATING); }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 304 "120++lex.l"
{ return tokenize(FLOATING); }
	YY_BREAK
case 153:
/* rule 153 can match eol */
YY_RULE_SETUP
#line 306 "120++lex.l"
{ return tokenize(CHARACTER); }
	YY_BREAK
case 154:
/* rule 154 can match eol */
YY_RULE_SETUP
#line 307 "120++lex.l"
{ return tokenize(CHARACTER); }
	YY_BREAK
case 155:
/* rule 155 can match eol */
YY_RULE_SETUP
#line 309 "120++lex.l"
{ return tokenize(STRING); }
	YY_BREAK
case 156:
/* rule 156 can match eol */
YY_RULE_SETUP
#line 310 "120++lex.l"
{ return tokenize(STRING); }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 312 "120++lex.l"
{ fprintf(stderr, "%d: unexpected character `%c'\n", lineno, yytext[0]); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
#line 314 "120++lex.l"
{
    
    yypop_buffer_state();
    pop_node(&filestack);
    if (filestack == NULL) {
        yyterminate();
        printf("ALL FILES PARSED!\n");
    }
    
    yylineno = 1;
    if (!YY_CURRENT_BUFFER) {
        printf("NO MORE BUFFERS!\n");
        yyterminate();
    }
}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 330 "120++lex.l"
ECHO;
	YY_BREAK
#line 2074 "<stdout>"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 560 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 560 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 559);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 330 "120++lex.l"




/*
%%

"#include <iostream>"   { iostream = 1;}
"#include <ctime>"      { ctime = 1; }
"#include <iomanip>"    { iomanip = 1; }
"#include <cmath>"      { cmath = 1; }
"#include <cstdlib>"    { cstdlib = 1; }
"#include <cstring>"    { cstring = 1; }
"#include <fstream>"    { fstream = 1; }
"#include <ofstream>"   { ofstream = 1; }
"#include <ifstrem>"    { ifstream = 1; }
"#include <string>"     { string  = 1; }

"#include"[ ]*\"[^\\"]+\"  { handle_include(); }
"using namespace std;"     { usingnamespacestd = 1; 

				if ( string == 1 ) {

     			   	typenametable_insert( "string" , classtable );

     		   	};

  			  	if ( iostream == 1 ) {

    				typenametable_insert( "ifstream" , classtable );
   				 	typenametable_insert( "ofstream" , classtable );
     		   	};
			}
			

"\n"					{ ++lineno; }
[\t\f\v\r ]+				{  }

"//".              { }// skip_until_eol(); }

"/" { }//skip_comment();//return token(COMMENT);

"{"                    { return token('{'); }
"<%"                    { return token('{'); }
"}"                    { return token('}'); }
"%>"                    { return token('}'); }
"["					{ return token('['); }
"<:"					{ return token('['); }
"]"					{ return token(']'); }
":>"					{ return token(']'); }
"("					{ return token('('); }
")"					{ return token(')'); }
";"					{ return token(';'); }
":"					{ return token(':'); }
"..."					{ return token(ELLIPSIS); }
"?"					{ return token('?'); }
"::"					{ return token(COLONCOLON); }
"."					{ return token('.'); }
".*"					{ return token(DOTSTAR); }
"+"					{ return token('+'); }
"-"					{ return token('-'); }
"*"					{ return token('*'); }
"/"					{ return token('/'); }
"%"					{ return token('%'); }
"^"					{ return token('^'); }
"xor"					{ return token('^'); }
"&"					{ return token('&'); }
"bitand"				{ return token('&'); }
"|"					{ return token('|'); }
"bitor"					{ return token('|'); }
"~"					{ return token('~'); }
"compl"					{ return token('~'); }
"!"					{ return token('!'); }
"not"					{ return token('!'); }
"="					{ return token('='); }
"<"					{ return token('<'); }
">"					{ return token('>'); }
"+="					{ return token(ADDEQ); }
"-="					{ return token(SUBEQ); }
"*="					{ return token(MULEQ); }
"/="					{ return token(DIVEQ); }
"%="					{ return token(MODEQ); }
"^="					{ return token(XOREQ); }
"xor_eq"				{ return token(XOREQ); }
"&="					{ return token(ANDEQ); }
"and_eq"				{ return token(ANDEQ); }
"|="					{ return token(OREQ); }
"or_eq"					{ return token(OREQ); }
"<<"					{ return token(SL); }
">>"					{ return token(SR); }
"<<="					{ return token(SLEQ); }
">>="					{ return token(SREQ); }
"=="					{ return token(EQ); }
"!="					{ return token(NOTEQ); }
"not_eq"				{ return token(NOTEQ); }
"<="					{ return token(LTEQ); }
">="					{ return token(GTEQ); }
"&&"					{ return token(ANDAND); }
"and"					{ return token(ANDAND); }
"||"					{ return token(OROR); }
"or"					{ return token(OROR); }
"++"					{ return token(PLUSPLUS); }
"--"					{ return token(MINUSMINUS); }
","					{ return token(','); }
"->*"					{ return token(ARROWSTAR); }
"->"					{ return token(ARROW); }

"asm"					{ return token(ASM); }
"auto"					{ return token(AUTO); }
"bool"					{ return token(BOOL); }
"break"					{ return token(BREAK); }
"case"					{ return token(CASE); }
"catch"					{ return token(CATCH); }
"char"					{ return token(CHAR); }
"class"					{ return token(CLASS); }
"const"					{ return token(CONST); }
"const_cast"				{ return token(CONST_CAST); }
"continue"				{ return token(CONTINUE); }
"default"				{ return token(DEFAULT); }
"delete"				{ return token(DELETE); }
"do"					{ return token(DO); }
"double"				{ return token(DOUBLE); }
"dynamic_cast"				{ return token(DYNAMIC_CAST); }
"else"					{ return token(ELSE); }
"enum"					{ return token(ENUM); }
"explicit"				{ return token(EXPLICIT); }
"export"				{ return token(EXPORT); }
"extern"				{ return token(EXTERN); }
"false"					{ return token(FALSE); }
"float"					{ return token(FLOAT); }
"for"					{ return token(FOR); }
"friend"				{ return token(FRIEND); }
"goto"					{ return token(GOTO); }
"if"					{ return token(IF); }
"inline"				{ return token(INLINE); }
"int"					{ return token(INT); }
"long"					{ return token(LONG); }
"mutable"				{ return token(MUTABLE); }
"namespace"				{ return token(NAMESPACE); }
"new"					{ return token(NEW); }
"operator"				{ return token(OPERATOR); }
"private"				{ return token(PRIVATE); }
"protected"				{ return token(PROTECTED); }
"public"				{ return token(PUBLIC); }
"register"				{ return token(REGISTER); }
"reinterpret_cast"			{ return token(REINTERPRET_CAST); }
"return"				{ return token(RETURN); }
"short"					{ return token(SHORT); }
"signed"				{ return token(SIGNED); }
"sizeof"				{ return token(SIZEOF); }
"static"				{ return token(STATIC); }
"static_cast"				{ return token(STATIC_CAST); }
"struct"				{ return token(STRUCT); }
"switch"				{ return token(SWITCH); }
"template"				{ return token(TEMPLATE); }
"this"					{ return token(THIS); }
"throw"					{ return token(THROW); }
"true"					{ return token(TRUE); }
"try"					{ return token(TRY); }
"typedef"				{ return token(TYPEDEF); }
"typeid"				{ return token(TYPEID); }
"typename"				{ return token(TYPENAME); }
"union"					{ return token(UNION); }
"unsigned"				{ return token(UNSIGNED); }
"using"					{ return token(USING); }
"virtual"				{ return token(VIRTUAL); }
"void"					{ return token(VOID); }
"volatile"				{ return token(VOLATILE); }
"wchar_t"				{ return token(WCHAR_T); }
"while"					{ return token(WHILE); }



[a-zA-Z_][a-zA-Z_0-9]*			{ return token(check_identifier(yytext) ); }//, classtable) ); }

"0"[xX][0-9a-fA-F]+{intsuffix}?		{ return token(INTEGER); }
"0"[0-7]+{intsuffix}?			{ return token(INTEGER); }
[0-9]+{intsuffix}?			{ return token(INTEGER); }

{fracconst}{exppart}?{floatsuffix}?	{ return token(FLOATING); }
[0-9]+{exppart}{floatsuffix}?		{ return token(FLOATING); }

"'"{chartext}*"'"			{ return token(CHARACTER); }
"L'"{chartext}*"'"			{ return token(CHARACTER); }

"\""{stringtext}*"\""			{ return token(STRING); }
"L\""{stringtext}*"\""			{ return token(STRING); }


.					{ fprintf(stderr, "%d: unexpected character `%s'\n", lineno, yytext); }


<<EOF>>                 { EOF(); }

%%

void EOF(){
    yypop_buffer_state();
    pop_node(&filestack);
    if (filestack == NULL)
    yyterminate() printf("ALL FILES PARSED!\n");
    
    yylineno = 1;
    if (!YY_CURRENT_BUFFER)
    printf("NO MORE BUFFERS!\n") yyterminate();
    
}

 */
///"/*"                    { skip_comment(); }
//"//"                    { skip_until_eol(); }
void prepare_token(int category)
{
    yytoken = token_new(category, yylineno, yytext,
    (const char *)list_back(yyfiles));
    struct node *n = node_new(TOKEN);
    n->token = yytoken;
    yylval.nodeptr = tree_new(NULL, n, NULL,
    (void (*)(void *, bool))&delete_tree);
}


/*
 * We use this routine instead a lex pattern because we don't need
 * to save the matched comment in the `yytext' buffer.
 */


/*
static void skip_comment(void)
{
	int c1, c2;

c1 = input();
c2 = input();

	while (c2 != EOF && !(c1 == '*' && c2 == '/')) {
		if (c1 == '\n')
			++lineno;
		c1 = c2;
        c2 = input();
	}
}

static void skip_until_eol(void)
{
	int c;

	while ((c = input()) != EOF && c != '\n')
		;
	++lineno;
}
//*/



 int tokenize(int category)
{
   // yytoken =
   prepare_token(category);
   //yytoken = create_token(category, yytext, yylineno, filestack->filename);
	//name.filename

    yylval.nodeptr = alctree(yytext, category, 0);
	//yylval.nodeptr->tok_text = yytoken;
   	return category;
}

void handle_include()
{
	
    char *fname = malloc(strlen(yytext)+1-strlen("#include \"\""));
    fname = strchr(yytext, '\"')+1;
    fname[strlen(fname)-1] = '\0';
    printf("%s\n",fname);
    yyin = fopen(fname,"r");
    push_node(&filestack, fname);
    yypush_buffer_state(yy_create_buffer(yyin, YY_BUF_SIZE));

}


void typenametable_insert(char *s, tableptr t){ //, int c){//
    /*
    log_debug("inserting typename %s", s);
    char *key = strdup(s);
    int *i = malloc(sizeof(*i));
    log_assert(key && i);
    
    *i = c;
    
    if (hasht_search(yytypes, key))
    log_lexical("typename %s previously declared", s);
    
    if (hasht_insert(yytypes, key, i) == NULL)
    log_error("failed to insert %s into yytypes table", s);
    */
 ///*
    if ( lookup( s, t ) == true ) {
         fprintf(stderr,
 	    "warning, %s is already in the typename table as a %s\n",
             s, s );
 	} else {

      printf("INSERTED %s: #include\n", s);
      insert_entry( s, t );

    }
 // */
}

static int check_identifier( char *s, tableptr t ) {
    
    int *c = hasht_search(yytypes, (void *)s);
    if (c)
    T(*c);
    else
    T(IDENTIFIER);
};

void delete_tree(void *data, bool leaf)
{
    struct node *n = data;
    if (n->token)
    token_free(n->token);
    free(data);
}

#undef T
#undef YYAPPENDTEXT
#undef YYAPPENDCHAR


/*
 if ( lookup( s , t ) == true ) {
 
 printf( "\"%s\" is in class table\n", s );
 
 return CLASS_NAME;
 
 } else {
 
 printf( "\"%s\" is a not in class table\n", s );
 return IDENTIFIER;
 
 }
 */

/*
 <<EOF>>                 {  yypop_buffer_state();
 pop_node(&filestack);
 if (filestack == NULL) {
 yyterminate();
 printf("ALL FILES PARSED!\n");
 };
 
 yylineno = 1;
 if (!YY_CURRENT_BUFFER) {
 printf("NO MORE BUFFERS!\n")
 yyterminate();
 };
 }
 
 
 */

